# Gradle settings
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Minecraft and mappings
minecraft_version=1.21.1
parchment=2024.11.17

# Project info
archives_name=ous
mod_version=1.0.0
maven_group=com.cahcap
mod_id=ous
mod_name=Once Upon a Season
mod_license=All Rights Reserved
mod_authors=YourNameHere, OtherNameHere
mod_description=A Minecraft mod about herbs and nature magic.

# Platform
enabled_platforms=neoforge

# Dependencies
architectury_api_version=13.0.8
fabric_loader_version=0.18.4
neoforge_version=21.1.215
jei_version=19.27.0.340

# Version ranges for neoforge.mods.toml
loader_version_range=[1,)
minecraft_version_range=[1.21.1]
