package com.cahcap.neoforge.common.datagen;

import com.cahcap.OusCommon;
import com.cahcap.neoforge.common.datagen.loot.ModBlockLootProvider;
import com.cahcap.neoforge.common.datagen.recipes.provider.ModRecipeProvider;
import com.cahcap.neoforge.common.datagen.tags.ModBlockTagsProvider;
import com.cahcap.neoforge.common.datagen.tags.ModItemTagsProvider;
import com.cahcap.neoforge.common.datagen.worldgen.ModWorldGenProvider;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.CachedOutput;
import net.minecraft.data.DataGenerator;
import net.minecraft.data.DataProvider;
import net.minecraft.data.PackOutput;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import net.neoforged.neoforge.data.event.GatherDataEvent;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.CompletableFuture;

/**
 * Main entry point for data generation. Registers loot/recipe/tag/worldgen
 * providers and starts a watchdog that forces JVM exit once every provider's
 * {@link DataProvider#run} future completes — works around NeoForge dev
 * runtime leaving non-daemon threads alive after datagen finishes.
 * <p>
 * Block model cleanup / multiblock split / voxelshapes / multiblock
 * blockstates are generated by {@code :common:processModels}, not here.
 */
@EventBusSubscriber(modid = OusCommon.MOD_ID, bus = EventBusSubscriber.Bus.MOD)
public class ModDataGenerator {

    /** Futures returned by each registered provider's {@code run()}. */
    private static final List<CompletableFuture<?>> providerFutures =
            Collections.synchronizedList(new ArrayList<>());

    @SubscribeEvent
    public static void gatherData(GatherDataEvent event) {
        DataGenerator generator = event.getGenerator();
        PackOutput packOutput = generator.getPackOutput();
        CompletableFuture<HolderLookup.Provider> lookupProvider = event.getLookupProvider();
        ExistingFileHelper existingFileHelper = event.getExistingFileHelper();

        if (event.includeServer()) {
            add(generator, new ModBlockLootProvider(packOutput, lookupProvider));
            add(generator, new ModRecipeProvider(packOutput, lookupProvider));

            ModBlockTagsProvider blockTagsProvider =
                    new ModBlockTagsProvider(packOutput, lookupProvider, existingFileHelper);
            add(generator, blockTagsProvider);
            add(generator, new ModItemTagsProvider(packOutput, lookupProvider,
                    blockTagsProvider.contentsGetter(), existingFileHelper));

            for (DataProvider p : ModWorldGenProvider.providers(
                    packOutput, lookupProvider, existingFileHelper)) {
                add(generator, p);
            }
        }

        OusCommon.LOGGER.info("Once Upon a Season data generation setup complete!");
        startExitWatchdog();
    }

    /**
     * Registers a provider and captures its {@code run()} future for the
     * watchdog.
     */
    private static void add(DataGenerator generator, DataProvider inner) {
        generator.addProvider(true, new DataProvider() {
            @Override
            public String getName() {
                return inner.getName();
            }

            @Override
            public CompletableFuture<?> run(CachedOutput cache) {
                CompletableFuture<?> f = inner.run(cache);
                providerFutures.add(f);
                return f;
            }
        });
    }

    /**
     * Daemon thread that waits for every registered provider future to
     * complete, then forces {@code System.exit(0)}. Works around
     * non-daemon threads in the NeoForge dev runtime that otherwise prevent
     * clean shutdown after runData finishes.
     */
    private static void startExitWatchdog() {
        Thread watchdog = new Thread(() -> {
            // Wait a tick so all providers get registered and start running.
            try {
                Thread.sleep(500);
            } catch (InterruptedException ignored) {
                return;
            }

            CompletableFuture<?>[] snapshot;
            synchronized (providerFutures) {
                snapshot = providerFutures.toArray(new CompletableFuture<?>[0]);
            }
            if (snapshot.length == 0) {
                // Nothing tracked (e.g. client-only run); don't force exit.
                return;
            }

            try {
                CompletableFuture.allOf(snapshot).get();
            } catch (Exception ignored) {
                // Ignore — we still want to try exiting cleanly.
            }

            // Tiny grace period for file writers / log flush.
            try {
                Thread.sleep(500);
            } catch (InterruptedException ignored) {
            }

            System.err.println("[Ous] data generation complete; forcing JVM exit.");
            System.exit(0);
        }, "Ous-datagen-exit-watcher");
        watchdog.setDaemon(true);
        watchdog.start();
    }
}
